
spring.datasource.url=jdbc:mysql://localhost:3306/mechconnect
spring.datasource.username=root
spring.datasource.password=0194

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=vPbmRoxXMmsF7SQNjV4Z+Ry4+fqIXpj7Qw0Q3WfzxG5Ye0xE3olwfMXNsmnR+lcD 
jwt.expiration-ms=86400000